weight: 1
languageCode: id
languageName: Bahasa Indonesia
hasCJKLanguage: false
pagination:
  pagerSize: 12
copyright: Karya ini dilisensikan di bawah Creative Commons Attribution-NonCommercial 4.0 International License.
