description: Hugo DoIt 主题官方文档
keywords:
  - Theme
  - Hugo
app:
  title: NgodingBang Blog
  noFavicon: false
  svgFavicon: ""
  iconColor: "#5bbad5"
  tileColor: "#da532c"
search:
  enable: true
  type: algolia
  contentLength: 4000
  placeholder: ""
  maxResultLength: 10
  snippetLength: 50
  highlightTag: em
  absoluteURL: false
  algolia:
    index: id_index
    appID: SVHWQLAYIJ
    searchKey: de9eabf079d30187f30df831e9622b53
  fuse:
    isCaseSensitive: false
    minMatchCharLength: 2
    findAllMatches: false
    location: 0
    threshold: 0.1
    distance: 100
    ignoreLocation: true
    useExtendedSearch: false
    ignoreFieldNorm: false
home:
  rss: 10
  profile:
    enable: true
    gravatarEmail: ngodingbang@gmail.com
    avatarURL: ""
    avatarLinkURL: ""
    title: ""
    subtitle: Teman ngoding-mu setiap saat.
    typeit: false
    social: true
    disclaimer: ""
  posts:
    enable: true
    paginate: 7
social:
  Angellist: ""
  Bandcamp: ""
  Behance: ""
  Bilibili: xxxx
  Bitbucket: ""
  BuyMeACoffee: ""
  Codepen: ""
  Deviantart: ""
  Devto: xxxx
  Douban: xxxx
  Dribbble: ""
  Email: xxxx@xxxx.com
  Facebook: ""
  Fivehundredpx: ""
  Flickr: ""
  Foursquare: ""
  FreeCodeCamp: ""
  Gitea: ""
  GitHub: xxxx
  Gitlab: ""
  Goodreads: ""
  Googlescholar: ""
  Hackernews: ""
  Instagram: ""
  Jsfiddle: ""
  Keybase: ""
  Kickstarter: ""
  Ko-Fi: ""
  Lastfm: ""
  Liberapay: ""
  Linkedin: ""
  Linktree: ""
  Mastodon: ""
  Matrix: ""
  Medium: ""
  Mix: ""
  Odnoklassniki: ""
  ORCID: ""
  Patreon: ""
  Paypal: ""
  Pinterest: ""
  QQ: ""
  QQGroup: ""
  Quora: ""
  Reddit: ""
  Researchgate: ""
  RSS: true
  Skype: ""
  Slidershare: ""
  Snapchat: ""
  Soundcloud: ""
  Spotify: ""
  Stackoverflow: ""
  Steam: xxxx
  Strava: ""
  Telegram: ""
  Thingiverse: ""
  Tumblr: ""
  Twitch: ""
  Twitter: ""
  Vine: ""
  VK: ""
  Weibo: xxxx
  Whatsapp: ""
  Wordpress: ""
  Xing: ""
  XMPP: ""
  Youtubechannel: ""
  Youtubecustom: ""
  Youtubelegacy: ""
  Zhihu: xxxx
  Diaspora:
    id: "@xxxx"
    prefix: https://yyyy/
sponsor:
  enable: false
  bio: 如果你觉得这篇文章对你有所帮助，欢迎赞赏~
  link: https://github.com/sponsors/HEIGE-PCloud
