description: Your best coding companion.
search:
  algolia:
    index: en_index
home:
  profile:
    subtitle: Your best coding companion.
sponsor:
  bio: If you find this post helpful, please consider sponsoring.
