title: NgodingBang
license: <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0" target="_blank">CC BY-NC 4.0</a>
app:
  title: NgodingBang
  noFavicon: false
  iconColor: #000e44
  tileColor: #000e44
keywords:
  - NgodingBang
  - Blog
  - Hugo
version: 0.3.X
defaultTheme: auto
gitRepo: https://github.com/ngodingbang/ngodingbang.github.io
fingerprint: sha256 # sha256 | sha384 | sha512 | md5
dateFormat: 2006-01-02
images:
  - /logo.webp
enablePWA: true
bundle: false
search:
  enable: true
  type: fuse
  contentLength: 4000
  maxResultLength: 10
  snippetLength: 300
  highlightTag: em
  absoluteURL: false
  algolia:
    appID: SVHWQLAYIJ
    searchKey: de9eabf079d30187f30df831e9622b53
  fuse:
    isCaseSensitive: false
    minMatchCharLength: 2
    findAllMatches: false
    location: 0
    threshold: 0.1
    distance: 100
    ignoreLocation: true
    useExtendedSearch: false
    ignoreFieldNorm: false
image:
  cacheRemote: true
  optimise: true
header:
  themeChangeMode: switch # switch | select
  title:
    logo: /logo.webp
    name: NgodingBang
    typeit: false
footer:
  enable: true
  custom: ""
  hugo: false
  hostedOn: <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
  copyright: true
  author: true
  since: 2024
  license: <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0" target="_blank">CC BY-NC 4.0</a>
section:
  paginate: 20
  dateFormat: 01-02
  rss: 10
  recentlyUpdated:
    enable: true
    rss: true
    days: 30
    maxCount: 10
list:
  paginate: 20
  dateFormat: 01-02
  rss: 10
home:
  rss: 10
  profile:
    enable: true
    gravatarEmail: ngodingbang@gmail.com
    typeit: false
    social: true
  posts:
    enable: true
    paginate: 7
social:
  GitHub: ngodingbang
  Instagram: ngodingbang
  Linkedin: ianrizky
  Medium: "@ngodingbang"
  RSS: true
  X: "ngodingbang"
  Youtubechannel:
    id: "@ngodingbang"
    prefix: https://www.youtube.com/
page:
  twemoji: true
  lightgallery: true
  ruby: true
  fraction: true
  seriesNavigation: true
  enableLastMod: true
  enableWordCount: true
  enableReadingTime: true
  instantpage:
    enable: true
  outdatedArticleReminder:
    enable: false
    reminder: 90
    warning: 180
  toc:
    enable: true
    keepStatic: false
    auto: true
  code:
    maxShownLines: 100
  table:
    sort: true
  header:
    number:
      enable: false
      format:
        h2: "{h2} {title}"
        h3: "{h2}.{h3} {title}"
        h4: "{h2}.{h3}.{h4} {title}"
        h5: "{h2}.{h3}.{h4}.{h5} {title}"
        h6: "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  math:
    enable: true
    blockLeftDelimiter: ""
    blockRightDelimiter: ""
    inlineLeftDelimiter: ""
    inlineRightDelimiter: ""
    copyTex: true
    mhchem: true
    mathjax: false
  mapbox:
    accessToken: pk.eyJ1IjoibmdvZGluZ2JhbmciLCJhIjoiY20wZGNuaGJwMDdxcjJrcHcyaDYxbGcwNCJ9.RwYKBkr74g89MXnV9zCERg
    lightStyle: mapbox://styles/mapbox/light-v10?optimize=true
    darkStyle: mapbox://styles/mapbox/dark-v10?optimize=true
    navigation: true
    geolocate: true
    scale: true
    fullscreen: true
  share:
    enable: true
    Facebook: true
    Linkedin: true
    Reddit: true
    Telegram: true
    X: true
    Whatsapp: true
  comment:
    enable: true
    disqus:
      enable: false
      shortname: ""
    gitalk:
      enable: false
      owner: ""
      repo: ""
      clientId: ""
      clientSecret: ""
    valine:
      enable: false
      appId: ""
      appKey: ""
      placeholder: ""
      avatar: mp
      meta: ""
      pageSize: 10
      lang: en
      visitor: true
      recordIP: false
      highlight: true
      enableQQ: false
      serverURLs: ""
      emoji: ""
    waline:
      enable: false
      serverURL: https://waline-comment-doit.vercel.app/
      pageview: true
      comment: true
    facebook:
      enable: false
      width: 100%
      numPosts: 10
      appId: ""
      languageCode: ""
    telegram:
      enable: false
      siteID: ""
      limit: 5
      height: ""
      color: ""
      colorful: true
      dislikes: false
      outlined: false
      dark: false
    commento:
      enable: false
    utterances:
      enable: true
      repo: ngodingbang/ngodingbang.github.io
      issueTerm: pathname
      label: ""
      lightTheme: github-light
      darkTheme: github-dark
    twikoo:
      enable: false
      envId: https://twikoo-comments-doit.vercel.app/
      region: ""
      path: ""
      cloudbase: true
      visitor: true
      commentCount: true
    vssue:
      enable: false
      platform: ""
      owner: ""
      repo: ""
      clientId: ""
      clientSecret: ""
    remark42:
      enable: false
      host: ""
      site_id: ""
      max_shown_comments: 15
      show_email_subscription: true
      simple_view: false
    giscus:
      enable: false
      dataRepo: ""
      dataRepoId: ""
      dataCategory: ""
      dataCategoryId: ""
      dataMapping: pathname
      dataStrict: "0"
      dataReactionsEnabled: "1"
      dataEmitMetadata: "0"
      dataInputPosition: bottom
      lightTheme: light
      darkTheme: dark
      dataLang: en
      dataLoading: lazy
    artalk:
      enable: false
      server: ""
      site: ""
      lite: false
      katex: true
      lightbox: false
      pageview: true
      commentCount: true
  library:
    css: {}
    js: {}
  seo:
    images: []
    publisher:
      name: Ngoding Bang
      logoUrl: /logo.webp
  related:
    enable: true
    count: 5
sponsor:
  enable: false
  link: https://github.com/ngodingbang/ngodingbang.github.io
typeit:
  speed: 100
  cursorSpeed: 1000
  cursorChar: "|"
  duration: -1
verification:
  google: cLm5w2LJxedbTMkyYbPHeUom7QvW2C3YPrqF82hBxQM
analytics:
  enable: true
  google:
    id: G-55J4FNKZ1X
    anonymizeIP: true
cookieconsent:
  enable: true
cdn:
  data: ""
compatibility:
  polyfill: false
  objectFit: false
