description: Teman belajar ngoding terbaikmu.
search:
  algolia:
    index: id_index
home:
  profile:
    subtitle: Teman belajar ngoding terbaikmu.
sponsor:
  bio: Bila Anda merasa postingan ini bermanfaat, mohon pertimbangkan untuk mensponsori.
